### ISSUE TITLE
Barcode scan requiring restart

### ISSUE THREAD

**Issue by eyassug** [JSI-ETH/Mobile-NPC#4]
That when using the camera to scan a barcode, it'll work for one barcode, but then the app needs to be restarted to scan another one.

**Comment by joshzamor** [comment]
From stakeholder call:
- this might be fixed, release might come Fri (4/16)

**Comment by joshzamor** [comment]
potential fix went out 4/19, in testing this week

**Comment by joshzamor** [comment]
from stakeholder call: 
* testing in Malawi found that you can continue scanning products without restarting app.
* recommend to close as fixed
